// Code generated by postprocess. DO NOT EDIT.

package payjpv2

import "net/http"

// ErrorFieldMapping defines the mapping between error field name and HTTP status code
type ErrorFieldMapping struct {
	FieldName  string
	StatusCode int
}

// ErrorFieldMappings is the list of error field mappings used by ParseAPIError
var ErrorFieldMappings = []ErrorFieldMapping{
	{"BadRequest", http.StatusBadRequest},
	{"NotFound", http.StatusNotFound},
	{"UnprocessableEntity", http.StatusUnprocessableEntity},
}
